base_url = "https://www.sfago2024.org"
title = "AGO 2024 San Francisco"
default_language = "en"
build_search_index = true
compile_sass = true
output_dir = "build"

[markdown]
smart_punctuation = true
